nodeLinker: pnp

packageExtensions:
  '@safe-global/safe-core-sdk-utils@*':
    dependencies:
      '@ethersproject/bignumber': '*'
  '@safe-global/safe-core-sdk@*':
    dependencies:
      '@ethersproject/bignumber': '*'
      '@ethersproject/bytes': '*'
  '@safe-global/safe-ethers-lib@*':
    dependencies:
      '@ethersproject/abstract-signer': '*'
      '@ethersproject/bignumber': '*'
  '@shazow/whatsabi@*':
    dependencies:
      '@ethersproject/web': '*'
  '@walletconnect/iso-crypto@*':
    dependencies:
      '@walletconnect/encoding': '*'
  'cspell@*':
    dependencies:
      '@cspell/cspell-types': '*'

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: '@yarnpkg/plugin-interactive-tools'

yarnPath: .yarn/releases/yarn-3.5.0.cjs
