compressionLevel: mixed

enableGlobalCache: false

nodeLinker: pnp

packageExtensions:
  "@safe-global/protocol-kit@*":
    dependencies:
      "@ethersproject/abstract-signer": "*"
      "@ethersproject/bignumber": "*"
      "@ethersproject/bytes": "*"
      "@types/bn.js": "*"
      bn.js: "*"
      web3-eth-contract: "*"
  "@shazow/whatsabi@*":
    dependencies:
      "@ethersproject/web": "*"
  "@walletconnect/iso-crypto@*":
    dependencies:
      "@walletconnect/encoding": "*"
  "@walletconnect/modal-ui@*":
    dependencies:
      lit-html: "*"
  cspell@*:
    dependencies:
      "@cspell/cspell-types": "*"
  zksync-web3@*:
    dependencies:
      "@ethersproject/hash": "*"
      "@ethersproject/web": "*"

yarnPath: .yarn/releases/yarn-4.3.1.cjs
