nodeLinker: pnp

packageExtensions:
  "@safe-global/protocol-kit@*":
    dependencies:
      "@ethersproject/abstract-signer": "*"
      "@ethersproject/bignumber": "*"
      "@ethersproject/bytes": "*"
      "@types/bn.js": "*"
      bn.js: "*"
      web3-eth-contract: "*"
  "@shazow/whatsabi@*":
    dependencies:
      "@ethersproject/web": "*"
  "@walletconnect/iso-crypto@*":
    dependencies:
      "@walletconnect/encoding": "*"
  "@walletconnect/modal-ui@*":
    dependencies:
      lit-html: "*"
  cspell@*:
    dependencies:
      "@cspell/cspell-types": "*"
  zksync-web3@*:
    dependencies:
      "@ethersproject/hash": "*"
      "@ethersproject/web": "*"

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: "@yarnpkg/plugin-interactive-tools"

yarnPath: .yarn/releases/yarn-3.7.0.cjs
