name: CI

on: [push]

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16
      - uses: actions/cache@v2
        with:
          path: "**/node_modules"
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}
      - run: yarn
        working-directory: ./extension
      - name: Run static checks
        run: yarn run check
        working-directory: ./extension
      - name: Build extension
        run: yarn build
        working-directory: ./extension
      - run: yarn
        working-directory: ./e2e-tests
      - name: Run end-to-end tests
        run: yarn start
        working-directory: ./e2e-tests
