name: End-to-end tests

on: [push]

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - uses: actions/cache@v3
        with:
          path: "**/node_modules"
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}
      - run: yarn
        working-directory: ./extension
      - name: Build extension
        run: yarn build
        working-directory: ./extension
      - run: yarn
        working-directory: ./e2e-tests
        env:
          PUPPETEER_SKIP_CHROMIUM_DOWNLOAD: "true"
      - name: Run end-to-end tests
        uses: mujo-code/puppeteer-headful@18.9.0
        env:
          CI: "true"
          SEED_PHRASE: ${{ secrets.E2E_TESTS_SEED_PHRASE }}
        with:
          args: cd ./e2e-test && yarn start
