name: End-to-end tests

on: [push]

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 21
          cache: "yarn"
          cache-dependency-path: "**/yarn.lock"
      - name: Build extension
        working-directory: ./extension
        run: |
          yarn install --immutable
          yarn build
      - run: yarn install --immutable
        working-directory: ./e2e-tests
        env:
          PUPPETEER_SKIP_CHROMIUM_DOWNLOAD: "true"
      - name: Run end-to-end tests
        uses: mujo-code/puppeteer-headful@18.9.0
        env:
          CI: "true"
          SEED_PHRASE: ${{ secrets.E2E_TESTS_SEED_PHRASE }}
        with:
          args: yarn --cwd ./e2e-tests start
      - name: Upload failing test screenshots
        if: failure()
        uses: actions/upload-artifact@v3
        with:
          name: failing-test-screenshots
          path: e2e-tests/output/screenshots
          retention-days: 7
