name: Deploy Landing Page

on:
  push:
    branches: main
    paths: "landing-page/**"

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy Landing Page
    steps:
      - uses: actions/checkout@main
      - uses: actions/setup-node@main
        with:
          node-version: 16
      - run: npm install -g yarn
      - run: yarn install --frozen-lockfile
        working-directory: ./landing-page
      - run: yarn build
        working-directory: ./landing-page

      - name: Deploy to Github Pages
        uses: JamesIves/github-pages-deploy-action@v4.3.3
        with:
          branch: gh-pages
          folder: ./landing-page/build
